# Generated by Django 5.0.2 on 2024-03-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
