# Generated by Django 5.0.2 on 2024-03-20 19:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_endereco_alter_endereco_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='geral/img/perfil/'),
        ),
    ]
