# Generated by Django 5.0.2 on 2024-04-16 22:02

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_profile_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='foto',
        ),
        migrations.CreateModel(
            name='FotoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='viagens/imgCarrosel/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_perfil', to='main.profile')),
            ],
        ),
    ]
