# Generated by Django 5.0.2 on 2024-04-16 22:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_profile_foto_fotoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='viagens/imgCarrosel/'),
        ),
        migrations.DeleteModel(
            name='FotoPerfil',
        ),
    ]
