# Generated by Django 5.0.2 on 2024-04-16 23:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_fotoviagem_remove_profile_foto_profile_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='foto',
        ),
        migrations.DeleteModel(
            name='FotoViagem',
        ),
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='geral/img/perfil/'),
        ),
    ]
