# Generated by Django 5.0.2 on 2024-04-17 01:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_profile_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(), upload_to='geral/img/perfil/')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='foto',
        ),
        migrations.AddField(
            model_name='profile',
            name='fotos',
            field=models.ManyToManyField(blank=True, to='main.photo'),
        ),
    ]
