# Generated by Django 5.0.2 on 2024-04-17 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_photo_remove_profile_foto_profile_fotos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='FotoPerfil',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fotos',
        ),
        migrations.AddField(
            model_name='profile',
            name='fotoPerfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='main.fotoperfil'),
        ),
    ]
