# Generated by Django 5.0.2 on 2024-04-17 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_photo_fotoperfil_remove_profile_fotos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fotoPerfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fotoperfil'),
        ),
    ]
