# Generated by Django 5.0.2 on 2024-04-17 02:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_profile_fotoperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='viagens/imgCarrosel/')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fotoPerfil',
        ),
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ManyToManyField(blank=True, to='main.fotoviagem'),
        ),
        migrations.DeleteModel(
            name='FotoPerfil',
        ),
    ]
