# Generated by Django 5.0.2 on 2024-04-17 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_fotoviagem_remove_profile_fotoperfil_profile_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='foto',
        ),
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fotoviagem'),
        ),
    ]
