# Generated by Django 5.0.2 on 2024-04-17 02:50

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_profile_foto_profile_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='perfil/')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fotoperfil'),
        ),
        migrations.DeleteModel(
            name='FotoViagem',
        ),
    ]
