# Generated by Django 5.0.2 on 2024-04-17 03:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_profile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='media/perfil/perfilpadrao.jpg', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='perfil/'),
        ),
    ]
