# Generated by Django 5.0.2 on 2024-05-06 18:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_profile_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos_album', models.ImageField(blank=True, default='static/perfil/img/perfilpadrao.jpg', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='viagens/')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='static/perfil/img/perfilpadrao.jpg', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='perfil/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='album',
            field=models.ManyToManyField(to='main.album'),
        ),
    ]
