# Generated by Django 5.0.2 on 2024-05-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_album_alter_profile_foto_profile_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='album',
            field=models.ManyToManyField(blank=True, to='main.album'),
        ),
    ]
