# Generated by Django 5.0.2 on 2024-06-04 22:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_profile_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='album',
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='static/perfil/img/perfilpadrao.jpg', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='lugares/'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
