# Generated by Django 5.0.2 on 2024-06-05 00:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_profile_album_alter_profile_foto_delete_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='static/perfil/img/perfilpadrao.jpg', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='perfil/'),
        ),
    ]
