# Generated by Django 5.0.2 on 2024-03-11 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('destinoA', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('nota', models.DecimalField(decimal_places=1, default=0, max_digits=2, null=True)),
                ('comentarios', models.ManyToManyField(blank=True, to='destinos.comentario')),
            ],
        ),
    ]
