# Generated by Django 5.0.2 on 2024-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0002_lugarturistico_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugarturistico',
            name='rating',
        ),
        migrations.AddField(
            model_name='comentario',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, 'QUATOR'), (5, 'CINCO')], default=1),
        ),
    ]
