# Generated by Django 5.0.2 on 2024-03-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0005_alter_comentario_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='nota',
        ),
    ]
