# Generated by Django 5.0.2 on 2024-06-04 22:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0006_remove_comentario_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarturistico',
            name='foto',
            field=models.ImageField(blank=True, default='static/perfil/img/perfilpadrao.jpg', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='perfil/'),
        ),
    ]
