# Generated by Django 5.0.2 on 2024-06-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0008_alter_lugarturistico_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarturistico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='lugares/'),
        ),
    ]
