# Generated by Django 5.0.2 on 2024-06-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0009_alter_lugarturistico_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino_comentarios', to='destinos.lugarturistico'),
        ),
    ]
