# Generated by Django 5.0.2 on 2024-06-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0010_comentario_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='destino',
        ),
    ]
