# Generated by Django 5.0.2 on 2024-06-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0012_remove_comentario_destinoa_comentario_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarturistico',
            name='url_foto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
